# Parse the small Kconfig-style .config file into CMake cache variables.

function(_app_config_set key value)
    string(STRIP "${value}" clean_value)
    string(TOUPPER "${clean_value}" upper_value)

    if(upper_value MATCHES "^(Y|YES|ON|TRUE|1)$")
        set(${key} ON CACHE BOOL "Loaded from .config" FORCE)
    elseif(upper_value MATCHES "^(N|NO|OFF|FALSE|0)$")
        set(${key} OFF CACHE BOOL "Loaded from .config" FORCE)
    else()
        string(REGEX REPLACE "^\"(.*)\"$" "\\1" clean_value "${clean_value}")
        set(${key} "${clean_value}" CACHE STRING "Loaded from .config" FORCE)
    endif()
endfunction()

function(load_app_config config_file)
    if(NOT EXISTS "${config_file}")
        return()
    endif()

    message(STATUS "Loading application config: ${config_file}")
    file(STRINGS "${config_file}" config_lines)
    foreach(line IN LISTS config_lines)
        string(STRIP "${line}" line)
        if(line MATCHES "^# (CONFIG_[A-Za-z0-9_]+) is not set$")
            _app_config_set("${CMAKE_MATCH_1}" "n")
        elseif(line MATCHES "^(CONFIG_[A-Za-z0-9_]+)=(.*)$")
            _app_config_set("${CMAKE_MATCH_1}" "${CMAKE_MATCH_2}")
        endif()
    endforeach()
endfunction()
